### PR TITLE
Fixed saving model from an admin popup

### PR DESCRIPTION
**Pull request by jokerejoker**
Fixes issue #253

### CODE REVIEW

**Comment by spectras** [comment]
Hello!

Good catch, thanks for reporting and finding a fix.
I think, however, it would probably better to just check for `'location' in redirect`. That's the actual intent here: fixing the redirect url if one is output by the superclass' method. Relying on its internal to guess when it will put a redirect url and when it will not seems more fragile than just checking for it.

Anyway, I'll have to add a test case and ensure it passes tests on all supported versions as well.

**Comment by jokerejoker** [comment]
Would you like me to do a change to reflect the desired check on the location key?

**Comment by spectras** [comment]
Thanks, but I'm planning to work on hvad this weekend so I will add that to the batch of fixes I have planned :)

**Comment by spectras** [comment]
Fix is on master and will be included in upcomping v1.3.0.

**Pull request closed without merging**
