### PR TITLE
Support for Django REST framework.

### PR DESCRIPTION
**Pull request by spectras**
We will be adding official support for Django REST framework.
This pull request will track progress.

As of today, this code works, but lacks some features, namely:
- translatable fields cannot be used in the serializer's meta settings: `fields`, `exclude`, `read_only_fields`. They are always included, period.
- test cases. This will not be merged until properly tested.
- documentation.

For those who want to help, or are not afraid of living on the edge and want REST support, you use it this way:
```python
from hvad.contrib.restframework import HyperlinkedTranslatableModelSerializer

class MyModelSerializer(HyperlinkedTranslatableModelSerializer):
    # your definition as usual
```
Doing this will include your translatable fields, with read/write access. Each object will also gain a `language_code` field. Including it when POST-ing or PUT-ing is mandatory. For PATCH-ing, it is only mandatory if a translatable field is included in the request.

As an alternative to specifying the language in the objects themselves, it is possible to set a `Content-Language` header on the HTTP request. If both the header and the field are present, the field will take precedence, allowing to override the language for a specific object of a set.

### CODE REVIEW

**Comment by ivasic** [comment]
Are there any plans on merging this soon, now that REST framework 3.1 is out?

**Comment by spectras** [comment]
Yes there are! I had just missed the news of REST framework 3.1 being released. Expect a merge and release this week.

**Comment by ivasic** [comment]
Great, thanks much

**Comment by spectras** [comment]
Done.
Release 1.2.0, just published, adds the REST support feature that was on this branch, with a few fixes due to some last-minute API tweaks on django rest framework.
REST support is documented, but I have some odd issues with readthedocs not updating for some reason.

By the way, I'd love to hear some feedback on the REST framework support API.

**Comment by ivasic** [comment]
First tests show it works perfectly. Will report if needed.

Thanks for the awesome work!

**Pull request closed without merging**
